Rewrite Memebot's command system to take advantage of discord.py's existing command infrastructure
super-cooper/memebot pull request #109
Opened 2022-07-04 23:32 UTC by super-cooper

The existing command infrastructure has been ripped out, and replaced with simple modules containing wrapped functions which implement command logic. The tradeoff with this new approach:

_GOOD:_
* Commands are simpler and interface more directly with discord.py
* Command registry is offloaded to discord.py, which simplifies Memebot's code as a whole
* Migrating to future slash commands and interactions will be easier
_BAD:_
* New commands are not as simple to implement for new contributors; requires more reading of longer and more complex documentation

The original approach to commands was to offload complexity onto the registry system so that new contributors could implement a new command by simply putting a class in a module in the commands package. What was learned:

1. There were no new contributors
2. Existing contributors did not like this system

As such, it has been gutted for discord.py's [command extension](https://discordpy.readthedocs.io/en/stable/ext/commands). Their infrastructure is easier to understand, but requires a bit more manual intervention to get new commands wired up and usable by Memebot.

The changes are as follows:
* Top-level commands are replaced with coroutine functions that manage their own logic and I/O after arguments are handed off by discord.py.
* Command coroutines are wrapped with a [`command` decorator](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.command), which converts the coroutine into a [`Command` object](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Command)
* Instead of receiving messages, commands now receive a [`Context` object](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#context), which carries the message along with just about any other information one could possibly want.
* Instead of receiving only strings as arguments and resolving relevant models or data structures on their own, arguments are converted to the relevant types automatically by discord.py
* The [`role`](src/commands/role.py) command is registered as a [`Group`](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#group), and its subcommands are linked to it via `Group`'s command decorator.
* Command errors are now handled with exceptions. A new [`exceptions` module](src/lib/exceptions.py) has been created. It currently houses the `MemebotUserError`, which is how we differentiate errors which we want to show to the user.
* All exceptions are examined by the new [`on_command_error` listener](src/memebot.py). Any `MemebotUserErrors` are relayed to the user along with the help text for the command which caused an error. Other exceptions are logged internally, and reported to the user as an "Internal error."
* The [`help` command](src/commands/help.py) extends discord.py's native [`DefaultHelpCommand` class](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#defaulthelpcommand) to replicate behavior baked into the original Memebot help command.
* The Memebot class has been replaced with an instance of discord.py's native [`Bot` class](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#bot) which allows us to wire our logic to discord.py's bot infrastructure
* Twitter integration is now initialized by registering [`process_message_for_interaction`](src/integrations/twitter.py) as an [`on_message` listener](src/memebot.py)

2022-07-04 23:36 UTC, super-cooper commented
It would probably be a good idea to test these changes in the bot testing server. I tested them myself but there may be things I missed.

2022-07-05 01:15 UTC, nhawke requested changes

2022-07-05 01:15 UTC, nhawke commented on src/commands/role.py
> +        raise exception.MemebotUserError
Should this have an error msg?

2022-07-05 01:15 UTC, nhawke commented on src/commands/role.py
> +    finally:
I think this should be `else` not `finally`? or it should be not inside a block at all.  Even if the `raise`s preempt it, using `finally` is less clear.

2022-07-05 01:15 UTC, nhawke commented on src/commands/role.py
> +    if len(target_role.members) == 0:
I think you should reverse these cases to reduce indentation (like you did in `leave()`). i.e. 

```python
if len(...) != 0:
    raise error 

# success case at top level indent
try:
 ...
```

2022-07-05 01:15 UTC, nhawke commented on src/commands/role.py
> +        finally:
same as previous commnet re: `finally` vs outside the block

2022-07-05 01:15 UTC, nhawke commented on src/commands/role.py
> +    finally:
same as above re `finally`

2022-07-05 01:15 UTC, nhawke commented on src/commands/role.py
> +    finally:
same as above re: `finally`

2022-07-05 01:15 UTC, nhawke commented on src/commands/role.py
> +async def role_list(ctx: discord.ext.commands.Context, target_role: Optional[discord.Role]):
I assume the decorator will automatically understand that `target_role` is an argument to the command. Is it able to get the role correctly? or does it pass it as a string and we have to do the lookup?

2022-07-05 02:14 UTC, super-cooper commented on src/commands/registry.py
> -"""


2022-07-05 02:20 UTC, super-cooper commented on src/commands/registry.py
> -"""
😔

2022-07-05 02:31 UTC, super-cooper commented on src/commands/role.py
> +        raise exception.MemebotUserError
Shouldn't. It will just give the help output for `!role`.

```
> !role

!role 

Controls creating, joining, leaving, and listing permissionless mentionable roles. These roles are intended to serve as "tags" to allow mentioning multiple users at once.

Commands:
  create Creates <role>
  delete Deletes <role> if <role> has no members.
  join   Adds caller to <role>
  leave  Removes caller from <role>
  list   List all roles managed by Memebot, or list all members of a role.

Type !help <command> for more info on a command.
```

This is the same behavior that using the bare `!role` had before.

2022-07-05 02:31 UTC, super-cooper commented on src/commands/role.py
> +    finally:
It was a `finally` block previously. I think it would make more sense for it to be outside of the statement.

2022-07-05 02:31 UTC, super-cooper commented on src/commands/role.py
> +    if len(target_role.members) == 0:
Done

2022-07-05 02:31 UTC, super-cooper commented on src/commands/role.py
> +        finally:
Done

2022-07-05 02:31 UTC, super-cooper commented on src/commands/role.py
> +    finally:
Done

2022-07-05 02:31 UTC, super-cooper commented on src/commands/role.py
> +    finally:
Done

2022-07-05 02:31 UTC, super-cooper commented on src/commands/role.py
> +async def role_list(ctx: discord.ext.commands.Context, target_role: Optional[discord.Role]):
Yes! The signature of the function reflects the signature of the command. It's quite nifty. User arguments are converted to the correct type at runtime by discord.py. See [here](https://discordpy.readthedocs.io/en/stable/ext/commands/commands.html#converters). Roles can be passed as a string matching the role name, an @ mention, or a numeric ID. It will be converted to a role before it is passed to the function. If there is not matching role, an error is thrown before the function is even called.

2022-07-05 02:44 UTC, nhawke approved these changes

2022-07-05 03:00 UTC, merged