Add spoiler tags to twitter links
super-cooper/memebot pull request #115
Opened 2022-07-31 02:30 UTC by nhawke

If the user sends a message with a twitter link, memebot will respond with links to quote tweets or video links if necessary. However, if the user send the twitter link within a spoiler tag, memebot sends its usual replies, but those replies are un-spoiled.

This change adds spoiler tags to memebot's replies if the user's twitter link is within a spoiled part of the message. 

fixes #114

2022-07-31 14:58 UTC, super-cooper requested changes
It's upsetting how difficult it is to parse spoilers :( I tried to experiment with regular expressions, but it doesn't seem solvable. I asked in the discord developers server if they had any recommendations. Hopefully they do. 

Beyond that, it looks good. There are a couple small things I'd like changed.

2022-07-31 14:58 UTC, super-cooper commented on src/lib/util.py
> +  return False
I've asked in the discord developers server if there's a regex or some easier way to do this. Does this account for bullshit like 

||||
vs.
||foo||||bar||

?

2022-07-31 14:58 UTC, super-cooper commented on src/lib/util.py
> +def maybe_make_link_spoler(message: str, spoil: bool) -> str:
spoler

2022-07-31 14:58 UTC, super-cooper commented on src/integrations/twitter.py
> +async def get_quote_tweet_urls(tweet_info: tweepy.models.Status, spoiled: bool) -> str:
I don't know why this was a coroutine, but now that we're changing the signature, we can get rid of `async` here.

2022-07-31 14:58 UTC, super-cooper commented on src/integrations/twitter.py
> +        return match[0], util.is_spoil(content, match.start())
Might it not be easier to just return the URL with spoiler tags right here rather than return a boolean and then have a separate function apply the tags?

2022-08-01 01:55 UTC, nhawke commented on src/lib/util.py
> +  format = "|| {} ||" if spoil else "{}"
Fixed

2022-08-01 01:55 UTC, nhawke commented on src/lib/util.py
> +from typing import Tuple, List
fixed.

2022-08-04 23:39 UTC, nhawke commented on src/integrations/twitter.py
> +        return match[0], util.is_spoil(content, match.start())
The boolean is convenient because more than just the matched URL may need to be spoiled (embeds, quotes)

2022-08-04 23:53 UTC, nhawke commented on src/lib/util.py
> +  return False
Yeah it works with that. I can ass a unittest if you don't believe it:

```
>>> def spoil_map(msg):
...     # replace spoiled chars in the string with '#'
...     return ''.join(['#' if u.is_spoil(msg, i) else msg[i] for i in range(len(msg))])
...
>>> msg = '||foo||||bar||'
>>> spoil_map(msg)
'||###||||###||'
```

2022-08-04 23:54 UTC, nhawke commented on src/lib/util.py
> +  return False
for the other example you gave: 

```
>>> msg2 = '||||'
>>> spoil_map(msg2)
'||||'
```

2022-08-10 02:26 UTC, super-cooper commented on src/integrations/twitter.py
> +        return match[0], util.is_spoil(content, match.start())
I don't understand what this means. We return the twitter URL, and a boolean that says whether or not it should be spoiled. We then apply spoiler tags to the URL if the boolean is true. Why not just return the Twitter URL with the spoiler tags right here and save a step? I'm not sure how the boolean enables us to do anything else later on.

2022-08-10 02:35 UTC, nhawke commented on src/integrations/twitter.py
> +        return match[0], util.is_spoil(content, match.start())
The twitter URL here is never sent, so we'd never need to wrap it in spoiler tags. It's just parsed to get the tweet ID

2022-08-10 02:44 UTC, super-cooper approved these changes

2022-08-10 02:44 UTC, super-cooper commented on src/integrations/twitter.py
> +        return match[0], util.is_spoil(content, match.start())
Right. I hate the multiple returns, but I do suppose there is no way around it

2022-08-10 02:45 UTC, merged