Improve basic logging for interaction infrastructure
super-cooper/memebot pull request #150
Opened 2023-02-18 18:11 UTC by super-cooper

- Add interaction wrapper for logging

The `interaction` function in our `log` module simply appends a highlighted interaction ID to the front of our log messages in order to facilitate tracking the flow of information for an interaction

- Improve basic logging for interaction infrastructure

Logs interactions on ingress and makes use of the new `log.interaction` function

2023-02-20 15:53 UTC, nhawke requested changes

2023-02-20 15:53 UTC, nhawke commented on src/log/__init__.py
> +import discord
Is it necessary to import this at runtime, or is this just for type checking? If the latter, i think this should be wrapped in a `if TYPE_CHECKING:` block. As in:

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import discord
```

That will guarantee that we dont have unintended side effects at runtime and make it more obvious that it's imported for type checking only

2023-02-25 16:07 UTC, super-cooper commented on src/log/__init__.py
> +import discord
Done

2023-02-26 05:01 UTC, nhawke approved these changes

2023-02-26 23:49 UTC, merged