Add source code volume to prevent docker image rebuild
super-cooper/memebot pull request #153
Opened 2023-03-14 01:03 UTC by nhawke

2023-04-09 19:29 UTC, super-cooper requested changes

2023-04-09 19:29 UTC, super-cooper commented on docker-compose.yaml
> +      - ./src:/opt/memebot/src
This sort of defeats the purpose of CI to build the image. Or really the purpose of having a docker image at all.

2023-04-09 19:29 UTC, super-cooper commented on docker/Dockerfile
> -
The code needs to be in the docker image. Otherwise, it's not a memebot docker image. 

The reason the image builds take longer than we want is because the test dependencies come after we pull in the source code. If the source code was the last thing in the Dockerifle, then it would cache all the previous steps and wouldn't need to install dependencies every time. We should change the dockerfile in this way:

```Dockerfile
FROM python:3.9.6-slim as build-release

# Copy in requirements.txt, create venv, install main dependencies

FROM build-release as build-test

# Copy in test-requirements.txt, source the venv from build-release, and then install test dependencies

FROM build-release as release

# Copy in source code, set entrypoint

FROM build-test as test

# Copy in source code, set entrypoint
```

More info on multi-stage builds: https://docs.docker.com/build/building/multi-stage/#use-multi-stage-builds

2023-05-28 21:54 UTC, nhawke commented on docker/Dockerfile
> -
Done (i think). There's now a significant speedup when re-building after a code change. These times are pretty representative of what I saw:

Old:
real    0m8.237s
user    0m0.262s
sys     0m0.000s

New:
real    0m3.560s
user    0m0.222s
sys     0m0.033s

I also used venv in the multi stage to make it simpler to copy over the dependencies to the final image.

2023-05-29 02:03 UTC, super-cooper approved these changes
Delicious

2023-05-29 02:03 UTC, merged