Add unit tests
super-cooper/memebot pull request #161
Opened 2023-06-07 11:05 UTC by super-cooper

This patch fully implements `pytest`-based unit tests for memebot. It currently tests all the commands plus Twitter integration. Most of the tests are fairly thorough. 

In order for the tests to run correctly, Memebot's code has been moved from the `src` directory to a root `memebot` package, as is typical for Python projects. The docker-compose file and README have been updated to reflect this as well. 

Resolves #31

2023-11-09 01:33 UTC, nhawke requested changes
When trying to run this, i ran into an issue trying to install emoji 2.0 (per requirements.txt) but i was able to install 2.8. We might need to bunp that version in the requirements.

2023-11-09 01:33 UTC, nhawke commented on tests/commands/test_hello.py
> +        f"Hello, {mock_interaction.user.display_name}!"
I dont think this is right. The Mock here is empty, so the `mock_interaction.user.display_name` will also be empty. While this test technically produces the right result, I think it would be better to populate that field so we can ensure the sent message actually accesses the property rather than something else that gives a `None`.

2023-11-09 01:33 UTC, nhawke commented on tests/commands/test_poll.py
> +    [["Mock answer" if i == j else None for i in range(5)] for j in range(5)],
Can you expand this out so the test cases are more explicit?

2023-11-09 01:33 UTC, nhawke commented on README.md
> +$ docker run --rm -it --entrypoint python3 memebot:test -m pytest [/path/to/test/package/or/module]
This isn't running all the tests for me: 

```
$ docker run --rm -it --entrypoint python3 memebot:test -m pytest
================================================= test session starts ==================================================
platform linux -- Python 3.9.6, pytest-7.1.2, pluggy-1.0.0
rootdir: /opt/memebot
collected 1 item

tests/test_pytest.py .                                                                                           [100%]

================================================== 1 passed in 0.01s ===================================================
```

2023-11-09 01:33 UTC, nhawke commented on tests/commands/test_poll.py
> +    [["Mock answer" if i == j else None for i in range(5)] for j in range(5)],
Can you expand out the test cases explicitly here?

2024-09-09 16:22 UTC, nhawke requested changes

2024-09-09 16:22 UTC, nhawke commented on tests/commands/test_poll.py
> +    ],
Each of these should be parameters at the top level, not nested inside an array.

Also you can lose the comment because the cases are self-explanatory now that the list comp is gone.

2024-09-09 16:22 UTC, nhawke commented on tests/commands/test_role.py
> +    mock_interaction.response.send_message.assert_awaited_once()
This doesn't need to be a helper. Better to explicitly do this in each case that uses it so it's more obvious what's happening in the test.

2024-09-09 16:22 UTC, nhawke commented on tests/commands/test_role.py
> +    await do_role_create_failure(
There shouldn't be this many layers of indirection for a test. It makes it hard to understand what the test is doing. Better for test logic to be repetitive but explicit.

Same goes for the other tests in this file. Helpers would make sense for test setup but for the critical logic section of the test it should just be explicity in the test funciton.

2024-09-09 16:22 UTC, nhawke commented on tests/fixtures/discord_fixtures.py
Are this and the twitter fixture actually used anywhere? I might just be missing something but I don't see the usage.

2024-09-09 16:22 UTC, nhawke commented on tests/commands/test_poll.py
> +    await do_poll_votes_test(mock_interaction, [], yes_no=True)
Can this test be combined with the other test which uses these helpers? then the helpers can just be inlined to avoid test logic indireciton.

2024-11-12 22:27 UTC, super-cooper reviewed
Addressed issues. Dependency stuff can get resolved after this is merged. Could be a python version incompatibility on your end, but once tests are merged, I can enable dependabot for Python packages which should handle issues like this going forward.

2024-11-12 22:27 UTC, super-cooper commented on tests/commands/test_poll.py
> +    await do_poll_votes_test(mock_interaction, [], yes_no=True)
I'd rather not. The test entrypoints exist to clarify what is being tested. If we combined them, we'd just need to gate it all with if-statements anyway. I think this is fine. I'm also gonna delete the poll command and all the tests after we merge this lmao

2024-11-12 22:27 UTC, super-cooper commented on tests/commands/test_role.py
> +    mock_interaction.response.send_message.assert_awaited_once()
Done.

2024-11-12 22:27 UTC, super-cooper commented on tests/commands/test_role.py
> +    await do_role_create_failure(
This is why I hate writing tests.

2024-11-13 00:14 UTC, nhawke approved these changes
Looks python to me

2024-11-13 00:14 UTC, nhawke commented on tests/commands/test_poll.py
> +    await do_poll_votes_test(mock_interaction, [], yes_no=True)
I disagree but moot anyway

2024-11-13 00:14 UTC, nhawke commented on tests/commands/test_poll.py
> +    ],
Oh my bad, `parameterize` just has a really stupid interface. Shoulda known better than to assume anything in python testing was sane...

2024-11-13 00:14 UTC, nhawke commented on tests/fixtures/discord_fixtures.py
I love implicit behavior and mocks !! Python tests and readability remain enemies

2024-11-13 01:34 UTC, merged