Split up commands into multiple files
super-cooper/memebot pull request #39
Opened 2020-11-02 22:56 UTC by super-cooper

**Does this improvement fix a bug/issue? Please describe.**
Commands are a bit cluttered in that they all exist in one file and are static functions in a class.

**What do you dislike about the feature in its current state?**
Big messy make angy :(

**Describe the solution you'd like**
 It would be better if commands were each in their own module and managed their own subcommands. in #19 we allocated these files, so this issue would require us to fill them in. I also would like to make it so that all commands have to implement a Commands interface, and then could register themselves as commands using a decorator.

**What tradeoffs are made by implementing your improvement?**
None that I can think of.

**Describe alternatives you've considered**
Keeping the same general implementation we have now, but still moving commands into their own dirs/files. I still think implementing an interface is much better, because then we can be strict about how commands are implemented, and generic about how they are used.

**Additional context**
This issue depends on the merging of #19 and #38.

2020-11-02 22:57 UTC, super-cooper commented
A lot of this got rushed at the end because if the breaking changes made to Discord's API. There are a number of TODO comments included in this patch. I don't really have ideas on how to redesign them at the moment, as that was part of the reason why this patch took so long.

2020-11-02 23:41 UTC, RobertWLeslie approved these changes
i swear I actually read it this time, and it looks good to me

2020-11-03 00:18 UTC, nhawke requested changes
Because this needs to get through ASAP, lot of my comments can be addressed with a TODO to consider / implement later. But there is at least one blocking comment that needs to be actually addressed before this merges

2020-11-03 00:18 UTC, nhawke commented on src/commands/command.py
> +    def callback(self, *args, **kwargs) -> None:
could you add docstring to this method (or a TODO to document it later)

2020-11-03 00:18 UTC, nhawke commented on src/commands/execution.py
> +        command, args = registry.parse_command_and_args(shlex.split(message.content))
Shouldn't this be passing `prepare_input(message.content)` instead of just the raw content?

2020-11-03 00:18 UTC, nhawke commented on src/commands/help/__init__.py
> +            top_level_command_registry))
I didn't know you could do this with strings, neat

2020-11-03 00:18 UTC, nhawke commented on src/commands/command.py
> +class Command:
this would also be helpful for the the TODO in the role help message (role/\_\_init__.py line 35)

2020-11-03 00:18 UTC, nhawke commented on src/commands/registry.py
> +        registry_entry = registry_entry.subcommand_registry[parent]
Should there be a check somewhere around here to ensure that registry_entry is valid at every step of this loop? (a TODO to add that would suffice)

2020-11-03 00:23 UTC, super-cooper commented on src/commands/__init__.py
> +registry.register_subcommand(role_parents, cmd_role_list)
Yeah, that is a plan for #52

2020-11-03 00:30 UTC, super-cooper commented on src/commands/help/__init__.py
> +            top_level_command_registry))
Hmm, I think you did :thinking_face:

2020-11-03 00:34 UTC, super-cooper commented on src/commands/registry.py
> +        registry_entry = registry_entry.subcommand_registry[parent]
What should we check for? We check that the top-level command is in the registry, and the loop will not continue if the subcommand is not registered for its parent.

2020-11-03 00:45 UTC, super-cooper reviewed
RFAL

2020-11-03 00:48 UTC, nhawke approved these changes
lgtm

2020-11-03 02:02 UTC, RobertWLeslie approved these changes
gtlm

2020-11-03 02:07 UTC, merged