Posts Embeded Quote Tweets and Media
super-cooper/memebot pull request #44
Opened 2020-08-26 00:37 UTC by RobertWLeslie

Feature that addresses issue #37
Also retrieves photos (and video) from tweet(s)

2020-09-01 04:00 UTC, super-cooper commented on src/memebot.py
> +        """Gets data of a tweet and checks if the tweet contains urls"""
This docstring should document what the parameters do.

2020-09-01 04:09 UTC, super-cooper commented on src/memebot.py
> +            if tweet_info.media:
I don't think we need any of this logic. We're only grabbing other linked tweets. We have a separate ticket for reacting to tweets with a certain number emoji to signify that there are multiple images in this, but I don't think we had any plans to post links of videos or pictures with the bot.

2020-09-01 04:12 UTC, super-cooper commented on src/memebot.py
> +                return self.get_tweet_urls(quoted_tweet_id, level+1, tweets + " " +quoted_tweet_url)
I think this would be very easy to do iteratively rather than recursively. That way, you wouldn't have to pass in a list as an argument, and we wouldn't have to worry about potential recursion terror.

2020-09-01 04:23 UTC, super-cooper commented on src/memebot.py
> +                quoted_tweet_url = tweet_info.urls[0].expanded_url
There is no guarantee that a tweet will be the first link in the tweet. I think it is a discussion worth having if we want to iterate through the URLs until we find a link to a tweet, or if we extract and iterate on all the tweet links. I am partial to the former because it is easier and avoids us creating a Grand Twitter Chaos Tree if a tweet links to a lot of other tweets.

2020-09-16 03:04 UTC, RobertWLeslie commented on src/memebot.py
> +import json
alpha-bet tically

2020-12-08 00:34 UTC, RobertWLeslie commented on src/main.py
> +
removed

2020-12-08 00:34 UTC, RobertWLeslie commented on src/main.py
> +
resolved

2020-12-08 00:35 UTC, RobertWLeslie commented on src/memebot.py
> +import twitter
done

2020-12-08 00:35 UTC, RobertWLeslie commented on .gitignore
> +.vscode/settings.json
fixed

2020-12-08 00:35 UTC, RobertWLeslie commented on src/memebot.py
> +    t_api = twitter.Api(
done re: `twitter_api`

2020-12-08 01:07 UTC, nhawke requested changes
I left my own comments, but also +1 to Adam's unresolved comments.

2020-12-08 01:07 UTC, nhawke commented on src/memebot.py
> +                await message.channel.send(self.get_tweet_urls(tweet_id, 0, ""))
Could this message be prepended with some short note explaining what the links are? e.g. rather than just the links, the message could start with something like 

```
Quoted tweets:
```

2020-12-08 04:30 UTC, super-cooper reviewed
I would also say hold off on resolving the old comments until the commit that addresses them has been pushed. I reviewed the two commits since I last reviewed, but most of the resolved comments didn't get fixed. It just makes the review a little confusing. If you want to resolve the comments as you fix them locally, I think that's fine, but maybe hold off on pushing more commits until all of the outstanding comments have been addressed+resolved. I think that's a happy solution for everyone.

2020-12-08 04:30 UTC, super-cooper commented on .gitignore
> +.vscode
I'll also add that this line should be `.vscode/`. It doesn't really matter, but it ensures we ignore the VSCode project directory instead of some other file called .vscode

2020-12-08 04:30 UTC, super-cooper commented on src/lib/constants.py
> +    ':4:':'4️⃣',
Herein lies the problem with the emoji map. `:one:`, `:two:`, etc. are the official names of these emojis, but it makes them impossible to iterate through lmao. I don't think it matters either way; I'm nuking this thing after this PR lands.

2020-12-08 04:46 UTC, super-cooper commented on src/memebot.py
> +        twitter_tokens = json.load(twitter_api_tokens)
re: this and your other comment below, I posted a comment on my last review about moving twitter logic to its own package, and then we could just make one call in `MemeBot.__init__` to initialize all our twitter stuff. I think this might be a good idea if we decide to use/integrate with other third party services/APIs in the future.

2020-12-08 04:46 UTC, super-cooper commented on src/memebot.py
> +    )
re: this and your other comment above, I posted a comment on my last review about moving twitter logic to its own package, and then we could just make one call in `MemeBot.__init__` to initialize all our twitter stuff. I think this might be a good idea if we decide to use/integrate with other third party services/APIs in the future.

2020-12-08 04:46 UTC, super-cooper commented on src/memebot.py
> +                await message.channel.send(self.get_tweet_urls(tweet_id, 0, ""))
Another insanely cheeky thought, maybe something we do down the road, but what about creating our own `discord.Embed` that mimics how the app does tweet embeds, and then posting that instead of the link?

2020-12-08 04:46 UTC, super-cooper commented on src/memebot.py
> +    def is_twitter(self, msg: str) -> bool:
Moving my comment here stating that this should be a static/module-level/package-level function, preferably in a separate twitter module/package.

2020-12-08 04:46 UTC, super-cooper commented on src/memebot.py
> +        return count
Also would add, if `tweet_info.media` has a `__len__` method, I am not sure this function needs to exist. I think just using `len(...` is simple enough and doesn't require any abstraction.

2020-12-22 18:33 UTC, super-cooper commented
I merged the latest commits into this branch with https://github.com/super-cooper/memebot/pull/44/commits/41081084160b5faeae6ced4c61891fb6ffc57c00. It doesn't look to me like this PR's branch in its current state works, but I don't think it worked before the merge either. Let me know if I missed or removed anything that I shouldn't have.

2020-12-22 18:40 UTC, super-cooper commented on src/memebot.py
> +                await message.channel.send(self.get_tweet_urls(tweet_id, 0, ""))
Also another thought, for the current solution, how about just using a 🔁?

2020-12-22 19:08 UTC, super-cooper requested changes
I decided to re-review from scratch since some history was lost when origin/master was merged into this branch. It is looking pretty good 🙂 

Some things are still broken, but since this is a work in progress commit I just marked those parts recognizing that they will be fixed/moved.

2020-12-22 19:08 UTC, super-cooper commented on src/memebot.py
> +        return bool(re.match(r'https:\/\/twitter\.com\b[-a-zA-Z0-9()@:%_\+.~#?&\/\/=]*', msg))
In order to speed up the regex checks on each word in the message, we should pre-compile the pattern with [`re.compile`](https://docs.python.org/3/library/re.html#re.compile) so it doesn't have to be recompiled for every word in the message. 

We should also maybe make this compiled pattern a constant that lives inside of the future twitter module/package/class so that it doesn't have to be compiled every time `has_twitter`/`has_tweet` is called. 

Since the regex is always the same, it doesn't make sense to compile it more than once.

2020-12-22 19:08 UTC, super-cooper commented on src/memebot.py
> +            tweets = tweets + " https://twitter.com/i/web/status/" + tweet_info.quoted_status.id_str
You can use `+=` here

2020-12-22 19:08 UTC, super-cooper commented on src/memebot.py
> +            tweets = tweets + " https://twitter.com/i/web/status/" + tweet_info.quoted_status.id_str
Should these be separated with a `\n`?

2020-12-22 23:23 UTC, super-cooper commented on src/memebot.py
> +        """Returns true if msg is a twitter link, otherwise returns False"""
How come you changed the name back?

2020-12-22 23:24 UTC, super-cooper requested changes
The changes look good! But there are still unresolved comments.

2020-12-23 00:11 UTC, RobertWLeslie commented on src/memebot.py
> +        return bool(re.match(r'https:\/\/twitter\.com\b[-a-zA-Z0-9()@:%_\+.~#?&\/\/=]*', msg))
Twitter URLs can also be referenced as `https://twitter.com/i/web/status/XXXXXXXXXXXXXXXXXX` Should I include this format as well and just have two regex patterns instead of what currently exists?

2020-12-23 00:48 UTC, RobertWLeslie commented on src/memebot.py
> +import shlex
import is now used

2020-12-23 02:56 UTC, super-cooper requested changes
It's looking great!! I have one nit, and [this unresolved commen from earlier](https://github.com/super-cooper/memebot/pull/44#discussion_r537951771), and then I think it is *done*.  🎉

2020-12-23 02:56 UTC, super-cooper commented on src/memebot.py
> +        self.twitter_url_pattern = re.compile(r'https:\/{2}twitter\.com\/([0-9a-zA-Z_]+|i\/web)\/status\/[0-9]+(\?s=\d+)?')
Using the raw string like you're doing here was a really good idea. Because of it, you can un-escape all of the `/` characters which will make the regex easier to read :)

2020-12-23 03:00 UTC, RobertWLeslie commented on src/memebot.py
> +                await message.channel.send(self.get_tweet_urls(tweet_id, 0, ""))
this was resolved by accomplishing @nhawke's suggestion of adding `Quoted tweets:`. Please check line 96 of `src/memebot.py` of the most recent commit.

2020-12-23 03:02 UTC, super-cooper commented on src/memebot.py
> +                await message.channel.send(self.get_tweet_urls(tweet_id, 0, ""))
Ah, gotcha. Nice 😎

2020-12-23 05:03 UTC, super-cooper approved these changes
There was a disaster with numeric emojis on Linux but that was fixed by https://github.com/super-cooper/memebot/pull/44/commits/b2cc028da2655bdc4b32f0202d6f0f2042fede98

2020-12-23 18:27 UTC, nhawke approved these changes

2020-12-23 18:41 UTC, merged