Better handle malformed role commands
super-cooper/memebot pull request #47
Opened 2020-09-05 03:54 UTC by nhawke

supplying a command such as `!role ?` would return a failure message that was malformed due to the missing third argument. Now, catch this ahead of time and return a help message when the action is not among the known actions.

2020-09-05 11:56 UTC, super-cooper requested changes
Only a couple small things

2020-09-05 11:56 UTC, super-cooper commented on src/commands/commands.py
> +                if can_manage and role.name != Commands.client.user.name:
This will create a merge conflict with #46. It should be removed from this PR.

2020-09-05 11:56 UTC, super-cooper commented on src/commands/commands.py
> +            if target_role == '':
Target role cannot be an empty string if it is `None`. If you want to catch both, you can `and` the conditions, or more concisely 
```python3
if not target_role:
```

2020-09-05 16:23 UTC, nhawke commented on src/commands/commands.py
> +                if can_manage and role.name != Commands.client.user.name:
yeah i'll wrestle with git after #46 is merged

2020-09-05 16:23 UTC, nhawke commented on src/commands/commands.py
> +            if target_role == '':
this was meant to be `if target_name == ''`. Fixed.

2020-09-05 16:25 UTC, super-cooper commented on src/commands/commands.py
> +                if can_manage and role.name != Commands.client.user.name:
You can just undo this change and there will be no conflict.

2020-09-05 16:26 UTC, super-cooper requested changes
Just remove the conflicting change and you will not have to wrestle with git.

2020-09-05 16:29 UTC, nhawke commented on src/commands/commands.py
> +                if can_manage and role.name != Commands.client.user.name:
true. done

2020-09-05 16:30 UTC, super-cooper approved these changes
lgtm

2020-09-08 15:37 UTC, RobertWLeslie approved these changes
lg2m

2020-09-08 15:40 UTC, merged