Commands module should automatically load commands
super-cooper/memebot pull request #52
Opened 2020-11-28 15:37 UTC by super-cooper

**Does this improvement fix a bug/issue? Please describe.**
N/A

**What do you dislike about the feature in its current state?**
Commands have to be manually registered in the constructor, which is inconvenient and unnecessary work for the command implementer.

**Describe the solution you'd like**
Dynamically load the the individual command modules when the `command` module loads, i.e. in `commands/__init__.py`. There is currently a placeholder function where this should take place.

**What tradeoffs are made by implementing your improvement?**
Adds a minor layer of complexity to command infrastructure, but is unlikely to need changes unless a command with wildly different format is created.

**Describe alternatives you've considered**
Manually adding commands is not a terrible solution, and solving this problem is pretty hard. 

**Additional context** 
With the refactors made in #39 , the command infrastructure was reworked in every desirable way except for automatic command module loading because Discord introduced [breaking changes](https://discordpy.readthedocs.io/en/latest/whats_new.html#v1-5-0) in their API and we needed to rush through the command module refactor so we could fix the `!role` command (see #51).)

2020-11-28 15:41 UTC, super-cooper commented
The changes included are pretty horrifying. I have set up machinery to automatically find and instantiate top-level commands at runtime, and those commands register themselves automatically. They also automatically register their subcommands as long as the top-level command is tagged with `@has_subcommands`. Along with this, there are some minor refactorings to remove some TODOs that were created when #31 was rammed through. 

The important thing to note here is that future commands need only be implemented in the right location, as a package, and tagged with `@has_subcommands` if applicable. No other wiring is necessary :)

2020-11-29 23:16 UTC, nhawke requested changes
Seems ugly but i guess it's better to have the ugliness contained to one place. LGTM other than some nits

2020-11-29 23:16 UTC, nhawke commented on src/commands/command.py
> +        if not name.islower() or any(not c.isalpha() for c in name):
`isalpha()` is a string method, so can't this be:
```py3
if not name.islower() or not name.isalpha():
# or
if not (name.islower() and name.isalpha()):
```
?

2020-11-30 06:35 UTC, super-cooper reviewed
RFAL

2020-11-30 06:35 UTC, super-cooper commented on src/commands/__init__.py
> +        cmd_class = getattr(pkg, pkg_name.capitalize())
The attr being getted is the class itself. I've changed the variable name and added comments to be more clear

2020-11-30 06:35 UTC, super-cooper commented on src/commands/command.py
> +        if not name.islower() or any(not c.isalpha() for c in name):
Done.

2020-11-30 06:37 UTC, super-cooper commented
@nhawke If you see any way to resolve the cyclic dependency let me know. It doesn't seem to actually affect the bot because the packages/modules are imported in the right order

2020-11-30 07:29 UTC, super-cooper commented
658165dda4d2904d8a160dccaf8647c9980524f3 should fix the circular import. I also think that moving registration out of the constructor is a much better move overall.

2020-11-30 08:09 UTC, nhawke approved these changes

2020-12-06 21:06 UTC, RobertWLeslie approved these changes
lg2m

2020-12-06 21:09 UTC, merged