Add caller's name to !hello response
super-cooper/memebot pull request #59
Opened 2020-12-09 01:41 UTC by nhawke

Now memebot can feel like a real human friend :)

closes #28

2020-12-09 02:36 UTC, super-cooper requested changes
nits

2020-12-09 02:36 UTC, super-cooper commented on src/commands/hello/__init__.py
> +        author: discord.abc.User = message.author
I don't think we need type annotations for local variables

2020-12-09 02:36 UTC, super-cooper commented on src/commands/hello/__init__.py
> +        return CommandOutput().set_text(msg)
While we're here, why not change it to 

```python3
return CommandOutput(CONTENT=msg)
```

2020-12-09 02:36 UTC, super-cooper commented on src/commands/hello/__init__.py
> +            msg: str = 'Hello!'
Out of curiosity, do we happen to know under what circumstances this would happen?

2020-12-09 03:07 UTC, nhawke commented on src/commands/hello/__init__.py
> +            msg: str = 'Hello!'
Not sure, but i want to guarantee that !hello is stable since it's the ping

2020-12-09 03:08 UTC, nhawke commented on src/commands/hello/__init__.py
> +        return CommandOutput().set_text(msg)
it aint workin boss

2020-12-09 03:10 UTC, super-cooper approved these changes
lgtm

2020-12-09 03:10 UTC, super-cooper commented on src/commands/hello/__init__.py
> +        return CommandOutput().set_text(msg)
disregard that, i suck

2020-12-09 05:20 UTC, super-cooper commented on src/commands/hello/__init__.py
> +        return CommandOutput().set_text(msg)
Actually, nevermind. This bug should be fixed by #60 :^)

2020-12-22 03:29 UTC, RobertWLeslie approved these changes
lgt2m

2020-12-22 15:49 UTC, merged