Fix role double-join errors
super-cooper/memebot pull request #65
Opened 2020-12-23 00:36 UTC by nhawke

Now, when a user joins a role they are already a member of, a proper
error message is sent instead of a duplicate success message.

fixes #49

2020-12-23 00:44 UTC, RobertWLeslie approved these changes
lg2m

2020-12-23 01:04 UTC, super-cooper requested changes
Looks good just trying to squeeze that one line under 120 characters

2020-12-23 01:04 UTC, super-cooper commented on src/commands/role/__init__.py
> +    return CommandOutput(command_status=status.FAIL).set_text(f"Memebot doesn't have permission to {action} role `@{target_name}`. "
```python3
    return CommandOutput(command_status=status.FAIL,
                         content=f"Memebot doesn't have permission to {action} role `@{target_name}`. "
                                 "Are you sure you configured Membot's permissions correctly?")
```

2020-12-23 01:07 UTC, nhawke commented on src/commands/role/__init__.py
> +    return CommandOutput(command_status=status.FAIL).set_text(f"Memebot doesn't have permission to {action} role `@{target_name}`. "
consider it done

2020-12-23 01:08 UTC, super-cooper approved these changes
lgtm

2020-12-29 15:34 UTC, RobertWLeslie approved these changes
lg2m

2020-12-30 00:28 UTC, merged