Migrate Twitter integration to tweepy
super-cooper/memebot pull request #71
Opened 2021-02-19 20:37 UTC by super-cooper

The python-twitter package is fully replaced by Tweepy, plus a few minor optimizations:

1. The tweet-checking regex now runs against the entire message, instead of once per word. The Twitter URL is then extracted via group matching.
2. Some functions have been renamed to be more clear.
3. Extracted quote tweet URLs now follow the `twitter.com/user/status/1234` format instead of `twitter.com/i/web/1234`.
4. API access is now by default read-only.

This patch was fairly painless, as tweepy happens to be reasonably similar to python-twitter.

Fixes #63.

2021-02-20 01:19 UTC, RobertWLeslie submitted a review, later dismissed
lg2m

2021-02-22 21:10 UTC, nhawke requested changes
Some minor logic nits that should be addressed

2021-02-22 21:10 UTC, nhawke commented on src/memebot.py
> +        if not tweets:
This will never be true. At least one URL is unconditionally appended to the string. The old logic should still work identically, and is cleaner.

2021-02-22 21:10 UTC, nhawke commented on src/memebot.py
> +                if quote_tweet_urls:
Like below in `get_quote_tweet_urls()`, the `quote_tweet_urls` will always be a non-empty string. Might be worth reworking how the function works if you want it to sometimes be empty. Otherwise, this branch can be removed.

2021-02-22 21:25 UTC, super-cooper reviewed
RFAL

2021-02-22 21:38 UTC, nhawke approved these changes
lgtm

2021-02-22 21:42 UTC, RobertWLeslie approved these changes
lg2m

2021-02-22 23:03 UTC, merged