Initial database implementation
super-cooper/memebot pull request #73
Opened 2021-02-22 20:57 UTC by super-cooper

In a big step for Memebot, we finally have a working database. I've chosen MongoDB since it's easy to use and it has a native Python driver. 

The changes introduced in this patch do not change behavior, but do change deployment just slightly.

1. The [Dockerfile](./docker/Dockerfile) has been moved to the `docker` directory, since I have now added a [docker-compose.yaml](./docker/docker-compose.yaml).
2. The [docker-compose.yaml](./docker/docker-compose.yaml) exists to define the project which now includes a database container. The database is spawned using the most basic possible configuration. There is a plan to add authentication in a future patch (#72).
3. The databse is presently not used for anything. A test function is run once at startup to ensure that a connection to the database is able to be made.
4. There is a basic framework for where database functionality should be written, although this is malleable and is free to be changed radically in the future. 
5. I added a [.dockerignore](./.dockerignore) file which will prevent unnecessary files from being copied to the Docker daemon when the image is built. This prevents the database files from being passed as well.
6. Adjustments to the [Dockerfile](./docker/Dockerfile) were also made. These were mostly borrowed from #61. I was required to do this due to updates made to the `aiohttp` package which require `gcc` to be installed on the host system. I figured if I was doing that, I may as well pull in the other optimizations alongside it.
7. Three new command-line configuration flags were added to enable/disable the database and set its URI.
8. `Command` objects received a new flag which will tell if they require use of the database to function. Presently, none of them do; however, I wanted to add this flag so that our commands could be modular. If the database were having issues, I would prefer not to have to shut down memebot completely while the problems are resolved. This flags allows database-dependent commands to not be registered if the databse is not available. 

Changes to, and additional, database functionality should be done at the will of future feature implementations. I didn't have a great idea for how all the abstraction should be worked out, so I left it pretty open-ended. 

Resolves #13.

2021-03-10 03:45 UTC, RobertWLeslie approved these changes
sure

2021-03-12 06:06 UTC, nhawke requested changes

2021-03-12 06:06 UTC, nhawke commented on src/db/__init__.py
> +    :return: True if the test succeeds
Does this raise an exception on failure?

2021-04-23 02:29 UTC, super-cooper commented on src/commands/__init__.py
> +            if not (subcommand.requires_database and not config.database_enabled):
Done

2021-04-23 02:29 UTC, super-cooper commented on src/commands/__init__.py
> +            if type(cmd_class.parent) is Command and not (instance.requires_database and not config.database_enabled):
Done

2021-04-23 02:29 UTC, super-cooper commented on src/config/__init__.py
> +                        action="store_false")
I felt that having the flag start with enable/disable might be annoying/confusing/hard to read if we had other enable/disable flags that kept that convention. I figured it would be easier to find the desired configuration at first glance if the flag started with the feature that it configures.

As far as the two flags, I know `--enable-database` is effectively useless, but I had read an article about standard conventions of these things and I can't find it anymore to justify my decision

2021-04-23 02:29 UTC, super-cooper commented on src/db/__init__.py
> +    :return: True if the test succeeds
No exceptions are listed on the docs. A quick look at the code shows that a `TypeError` can be thrown if a filter is provided, which we don't do.

2021-04-25 01:10 UTC, nhawke requested changes

2021-04-25 01:10 UTC, nhawke commented on src/db/__init__.py
> +    :return: True if the test succeeds
So if this can't throw an exception and can't return false, what purpose does it even serve?

2021-04-25 01:10 UTC, nhawke commented on src/config/__init__.py
> +                        action="store_false")
Noting our offline discussion: the two DB flags should be one `--nodb` flag instead (the Mongo standard)

2021-04-25 05:24 UTC, super-cooper commented on src/db/__init__.py
> +    :return: True if the test succeeds
Changed to a command that will throw an exception if it cannot connect.

2021-04-25 05:24 UTC, super-cooper commented on src/config/__init__.py
> +                        action="store_false")
Done

2021-04-25 05:42 UTC, nhawke submitted a review, later dismissed

2021-04-28 00:43 UTC, nhawke approved these changes

2021-05-04 23:47 UTC, RobertWLeslie approved these changes
lg2m

2021-05-05 11:05 UTC, merged